//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdooNet.Apps.Services.SyncFinanca.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OdooNet.Apps.Services.SyncFinanca.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM001.
        /// </summary>
        internal static string FIN5_DATABASE {
            get {
                return ResourceManager.GetString("FIN5_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\SQL2012.
        /// </summary>
        internal static string FIN5_HOSTNAME {
            get {
                return ResourceManager.GetString("FIN5_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FIN5_PASSWORD {
            get {
                return ResourceManager.GetString("FIN5_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string FIN5_USERNAME {
            get {
                return ResourceManager.GetString("FIN5_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        internal static string ODOO_COMPANY {
            get {
                return ResourceManager.GetString("ODOO_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitnami_odoo.
        /// </summary>
        internal static string ODOO_DATABE {
            get {
                return ResourceManager.GetString("ODOO_DATABE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.redis-stock.com.
        /// </summary>
        internal static string ODOO_HOSTNAME {
            get {
                return ResourceManager.GetString("ODOO_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string ODOO_ISSL {
            get {
                return ResourceManager.GetString("ODOO_ISSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCPVO3K385783XFO.
        /// </summary>
        internal static string ODOO_PASSWORD {
            get {
                return ResourceManager.GetString("ODOO_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8069.
        /// </summary>
        internal static string ODOO_PORT {
            get {
                return ResourceManager.GetString("ODOO_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlrpc@redis-stock.com.
        /// </summary>
        internal static string ODOO_USERNAME {
            get {
                return ResourceManager.GetString("ODOO_USERNAME", resourceCulture);
            }
        }
    }
}
